server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
#  security:
#    user:
#      name: user
#      password: 111111

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
fq:
  jwt:
    header: Authorization
    expire: 604800 #7天，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h
